intern/intern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('main/', include('main.urls')),
    path('admin_manage/', include('admin_manage.urls')),
]

urlpatterns += staticfiles_urlpatterns()

intern/main/urls.py
from django.urls import path
from . import views
from .views import *
app_name="main"

urlpatterns = [
    path("", views.index, name="index"),


    #ข่าว
    path('news', views.news, name="news"),
    path('news/<int:number>', views.news_content, name="news_content"),

    
    path('CompanyList', views.company, name="company"),
    path('Step1', Step1Form.as_view(), name="Step1"),
    path('Step2Admin',Step2Form.as_view(), name="Step2Admin"),
    path('Step2', views.step2U , name="Step2"),
    path('Step2/<str:pk>', views.step2A , name="Step2A"),
    path('Step1toPDF', views.Step1toPDF, name="Step1toPDF"),
    path('Step2toPDF', views.Step2toPDF, name="Step2toPDF"),
    path('Step3', views.step3, name="Step3"),
    path('Step4', views.step4, name="Step4"),
    path('Step5', views.step5, name="Step5"),
]
   

intern/user/urls.py
from django.urls import path

from . import views

app_name="user"

urlpatterns = [
	path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

intern/main/models.py
from ctypes import addressof
import email
from django.contrib.auth.models import User
from wsgiref.headers import Headers
from django.db import models
from django.utils import timezone
from matplotlib.pyplot import title

from .utils import upload_to
from .validators import validate_file_extension

# Create your models here.
class News(models.Model):
    header = models.CharField(max_length=150, null = True,)
    pdf = models.FileField(blank=True,null=True)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.header

class Company(models.Model):

    Company	= models.CharField(max_length=150, null = True,)
    Description = models.CharField(max_length=150, null = True,)
    Published = models.DateTimeField(default=timezone.now)
    close = models.DateTimeField(default=None)
    link = models.URLField(max_length=200,null = True,)

    def __str__(self):
        return self.Company


class Form(models.Model):
    class title(models.TextChoices):
        นางสาว = "นางสาว"
        นาง = "นาง"
        นาย = "นาย"

    user=models.ForeignKey(User,default=None, on_delete=models.PROTECT)
    nameTitle = models.CharField(max_length=100,
        choices=title.choices,
        default=None,
        )
    name = models.CharField(max_length=150, null = True,)
    sername = models.CharField(max_length=150, null = True,)
    studentID = models.CharField(max_length=10, null = True,)
    date = models.DateTimeField(default=timezone.now)
    major = models.CharField(max_length=150, null = True,)
    company = models.CharField(max_length=150, null = True,)
    addresscompany = models.CharField(max_length=150, null = True,)
    destination = models.CharField(max_length=150, null = True,)
    phone = models.CharField(max_length=10, null = True,)
    email = models.CharField(max_length=150, null = True,)
    booknumber = models.CharField(max_length=50, null = True,default=0)

    def __str__(self):
            return self.name

            
class Documentstep3 (models.Model):
    filename = models.CharField(max_length=100)
    attachment = models.FileField(upload_to=upload_to,validators=[validate_file_extension],null=True)
    
    def __str__(self):
        return self.filename
    
    def delete(self, *args, **kwargs):
        self.attachment.delete()
        super().delete(*args, **kwargs)

class Documentstep4 (models.Model):
    filename = models.CharField(max_length=100)
    attachment = models.FileField(upload_to=upload_to,validators=[validate_file_extension],null=True)
    
    def __str__(self):
        return self.filename
    
    def delete(self, *args, **kwargs):
        self.attachment.delete()
        super().delete(*args, **kwargs)
        
class Documentstep5 (models.Model):
    filename = models.CharField(max_length=100)
    attachment = models.FileField(upload_to=upload_to,validators=[validate_file_extension],null=True)
    
    def __str__(self):
        return self.filename
    
    def delete(self, *args, **kwargs):
        self.attachment.delete()
        super().delete(*args, **kwargs)
        

intern/main/forms.py
from django.forms import widgets
from django.http import request




from .models import *
from django import forms


class Step1Forms(forms.ModelForm):

    class Meta:
        model = Form
        fields = ('nameTitle','name','sername','studentID','date','major','company','addresscompany','destination','phone','email') 
        widgets = {'name': forms.TextInput,
        'sername': forms.TextInput,'studentID':forms.TextInput,'date': forms.SelectDateWidget,'major':forms.TextInput,'company':forms.TextInput,'addresscompany':forms.TextInput,
        'destination':forms.TextInput,'phone':forms.TextInput,'email':forms.TextInput,}

class Step2Forms(forms.ModelForm):

    class Meta:
        model = Form
        fields = ('booknumber',) 
        widgets = {'booknumber':forms.TextInput}
        
class Step3Forms(forms.ModelForm):
    class Meta:
        model = Documentstep3
        fields = ('filename','attachment')
        
    def __init__(self, *args, **kwargs):
        super(Step3Forms, self).__init__(*args, **kwargs)
        
        self.fields['filename'].widget.attrs.update(style='max-width: 50em')

class Step4Forms(forms.ModelForm):
    class Meta:
        model = Documentstep4
        fields = ('filename', 'attachment')

    def __init__(self, *args, **kwargs):
        super(Step4Forms, self).__init__(*args, **kwargs)

        self.fields['filename'].widget.attrs.update(style='max-width: 50em')
        
class Step5Forms(forms.ModelForm):
    class Meta:
        model = Documentstep5
        fields = ('filename','attachment')
        
    def __init__(self, *args, **kwargs):
        super(Step3Forms, self).__init__(*args, **kwargs)
        
        self.fields['filename'].widget.attrs.update(style='max-width: 50em')
        

intern/main/views.py
import re
from sys import intern
from turtle import up
from flask_login import logout_user
from platformdirs import user_documents_dir
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics
from ast import Delete, For
from email.mime import application
import os
import io
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen.canvas import Canvas
from reportlab.lib.utils import ImageReader
from unittest import result
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib import messages
from matplotlib import dates
# from matplotlib.style import context
from numpy import full

from .models import *
from django.template.loader import *
from django.db.models import Sum
from django.core.files.storage import *
from django.http import *
from django.shortcuts import render, get_object_or_404
from shutil import copyfile
from reportlab.pdfgen import canvas
from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa
from io import *
from django.forms.widgets import NullBooleanSelect
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from django.http import HttpResponseRedirect,Http404
from django.urls import reverse
from django.views.generic.edit import CreateView
from .forms import *
from django.urls import reverse_lazy

from django.shortcuts import render,redirect

from . import views
# Create your views here.

from django.contrib.auth.models import User

from .models import *
# Create your views here.
# main


def index(request):
    if not request.user.is_authenticated:
        return HttpResponseRedirect(reverse("user:login"))
    else:
        return render(request, "main/index.html")


def news(request):
    news = News.objects.all()
    context = {"news": news}
    return render(request, "main/news.html", context)


def company(request):
    company = Company.objects.all()
    context = {"company": company}
    return render(request, "main/companylist.html", context)


def news_content(request, number):
    fs = FileSystemStorage()
    file = (get_object_or_404(News, pk=number)).pdf
    filename = os.path.basename(file.name)

    if fs.exists(filename):
        with fs.open(filename) as pdf:
            response = HttpResponse(pdf, content_type="application/pdf")
            response['Content-Disposition'] = 'inline; filename = news.pdf'

            return response
    else:
        return HttpResponseNotFound



# from django.template.loader import *

def Step1toPDF(request):

    buffer = io.BytesIO()
    # ดึงไฟล์ THSarabunNew.ttf มาลงทะเบียนฟอนต์ในโค้ด
    pdfmetrics.registerFont(TTFont('THSarabunIT๙', 'THSarabunIT๙.ttf'))
    form = get_object_or_404(Form, user=request.user)
    c = canvas.Canvas(buffer)  # ไฟล์ที่จะเขียน
    c.setFont("THSarabunIT๙", 14)  # กำหนดฟอนต์ที่ใช้ และขนาดคือ 30
    date = form.date.strftime(" %m/%d/%Y ")
    c.setTitle("แบบฟอร์มขอหนังสือขอความอนุเคราะห์ฝึกงานภาคฤดูร้อน/สหกิจศึกษา")
    # กำหนดพิกัดที่เขียนและข้อความที่เขียน
    c.drawString(
        180, 780, "แบบฟอร์มขอหนังสือ ขอความอนุเคราะห์ฝึกงานภาคฤดูร้อน/สหกิจศึกษา")
    c.drawString(
        190, 750, "**** กรุณาเขียนตัวบรรจง เพื่อความถูกต้องในการพิมพ์หนังสือ ****")
    c.drawString(400, 710, "วันที่ " + date)
    c.drawString(80, 670, "ชื่อนักศึกษา   "+form.nameTitle+form.name +
                 "    "+form.sername + "      เลขทะเบียน     "+form.studentID)
    c.drawString(80, 640, "เป็นนักศึกษา " + form.major)
    c.drawString(
        80, 610, "ชื่อบริษัท (ที่จะไปฝึกงาน/สหกิจกษา) " + form.company)
    c.drawString(80, 580, "ที่อยู่บริษัท (ถ้ามี) " + form.addresscompany)
    c.drawString(
        80, 550, "หนังสือขอความอนุเคราะห์การฝึกงาน/สหกิจศึกษา เรียน (ตําแหน่ง)  " + form.destination)
    c.drawString(80, 520, "เบอร์โทรติดต่อนักศึกษา   " +
                 form.phone + "   E-mail   " + form.email)

    c.showPage()
    c.save()  # บันทึกไฟล์
    buffer.seek(0)
    return FileResponse(buffer, as_attachment=True, filename='แบบฟอร์มขอหนังสือขอความอนุเคราะห์ฝึกงานภาคฤดูร้อน/สหกิจศึกษา.pdf')

    # pattern = get_object_or_404(Form)
    template_path = 'main/toPDF.html'
    context = {'form': "ANUDCHANA อนุชนา 6210612575 ", }
    #  'paatern' : pattern}
    response = HttpResponse(content_type='application/pdf')
    response['Content-Dinposition'] = 'fliename = "test.pdf"'
    template = get_template(template_path)
    html = template.render(context)
    # pdf = render_to_pdf('main/toPDF.html',data)
    # return HttpRequest(pdf , content_type='application/pdf')
    pisa_status = pisa.CreatePDF(
        html.encode("UTF-8"), dest=response)
    if pisa_status.err:
        return HttpResponse('We had some error <pre>'+html+'</pre>')
    return response
    return FileResponse(buffer, as_attachment=True, filename='hello.pdf')


class Step1Form(CreateView):
    model = Form
    form_class = Step1Forms
    template_name = 'main/step1.html'
    success_url = reverse_lazy('main:Step2')
    
    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.booknumber = None
        return super().form_valid(form)

class Step2Form(CreateView):
    pass
    # model = Form
    # form_class = Step1Forms
    # template_name = 'main/start.html'
    # 

    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     return super().form_valid(form)


def Step2toPDF(request):
    
    buffer = io.BytesIO() 
    
    form = get_object_or_404(Form, user=request.user)
    c = canvas.Canvas(buffer)  
    
    logo = ImageReader('logo.png')
    sig = ImageReader('image.png')
    date = form.date
    month_name = 'x มกราคม กุมภาพันธ์ มีนาคม เมษายน พฤษภาคม มิถุนายน กรกฎาคม สิงหาคม กันยายน ตุลาคม พฤศจิกายน ธันวาคม'.split()[date.month]
    thai_year = date.year + 543
    pdfmetrics.registerFont(TTFont('THSarabunIT๙', 'THSarabunIT๙.ttf'))
    c.setFont("THSarabunIT๙", 14)  
    c.drawImage(logo,260,730, mask='auto',width=80 ,height=80)
    c.drawImage(sig,295,235, mask='auto',width=130 ,height=40)
    c.drawString(80, 740, "ที่ "+form.booknumber)
    c.drawString(400, 740, "คณะวิศวกรรมศาสตร์")
    c.drawString(400, 720, "มหาวิทยาลัยธรรมศาสตร์ ศูนย์รังสิต")
    c.drawString(400, 700, "อ. คลองหลวง จ. ปทุมธานี ๑๒๑๒๐")
    c.drawString(320, 660, "%d %s %d "%(date.day, month_name, thai_year))
    c.drawString(80, 620, "เรื่อง ขอความอนุเคราะห์นักศึกษาฝึกงานภาคฤดูร้อน")
    c.drawString(80, 590, "เรียน " + form.destination)
    c.drawString(80, 560, "สิ่งที่ส่งมาด้วย แบบตอบรับนักศึกษาฝึกงานภาคฤดูร้อน")
    c.drawString(
        150, 530, "ด้วย ภาควิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์   คณะวิศวกรรมศาสตร์   มหาวิทยาลัยธรรมศาสตร์")
    c.drawString(
        80, 510, "ได้กำหนดวิชาการฝึกงานทางวิศวกรรมคอมพิวเตอร์ไว้ในหลักสูตร โดยมีนโยบายที่จะส่งเสริมให้นักศึกษาชั้นปีที่ ๓ ได้มี")
    c.drawString(
        80, 490, "ประสบการณ์และความรอบรู้จากการทำงานจริง ตลอดจนรู้จักใช้ความรู้จากการศึกษามาประยุกต์เข้ากับการทำงาน")
    c.drawString(
        150, 460, "ในการนี้ ภาควิชาฯจึงขอความอนุเคราะห์ให้นักศึกษาดังรายชื่อต่อไปนี้")
    c.drawString(120, 440, form.nameTitle + form.name + "   " +
                 form.sername + "   เลขทะเบียน   " + form.studentID + "   " + form.major)
    c.drawString(
        80, 410, "ได้มีโอกาสเข้าฝึกงานในหน่วยงานของท่าน ช่วงปิดภาคฤดูร้อน ระหว่างวันที่ ๖ มิถุนายน ถึงวันที่ ๓๑ กรกฎาคม ๒๕๖๕")
    c.drawString(
        80, 390, "เป็นเวลาไม่น้อยกว่า   ๖  สัปดาห์ติดต่อกัน  (ไม่น้อยกว่า   ๒๔๐  ชั่วโมง)   ภาควิชาฯ   หวังเป็นอย่างยิ่งว่าจะได้รับความ")
    c.drawString(80, 370, "อนุเคราะห์จากท่าน ในครั้งนี้")
    c.drawString(
        150, 340, "จึงเรียนมาเพื่อโปรดพิจารณาให้ความอนุเคราะห์ด้วย   จักขอบพระคุณยิ่ง")
    c.drawString(320, 310, "ขอแสดงความนับถือ")
    c.drawString(280, 210, "(ผู้ช่วยศาสตราจารย์ ดร.พิศาล แก้วประภา)")
    c.drawString(275, 190, "หัวหน้าภาควิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์")
    c.drawString(80, 100, "ภาควิชาวิศวกรรมไฟฟ้าและคอมพิวเตอร์")
    c.drawString(80, 80, "โทร. ๐ ๒๕๖๔ ๓๐๐๑ - ๙ ต่อ ๓๐๓๗")
    c.drawString(80, 60, "อีเมล ece@engr.tu.ac.th")

    c.showPage()
    c.save()  # บันทึกไฟล์
    buffer.seek(0)
    # ,as_attachment=True
    return FileResponse(buffer, filename='หนังสือขอความอนุเคราะห์ฝึกงานภาคฤดูร้อน/สหกิจศึกษา.pdf')

# class Step2Form(CreateView):
#     model = Form
#     form_class = Step2Forms
#     template_name = 'main/step2_Admin.html'
#     success_url = reverse_lazy('main:Step2')

#     def form_valid(self, form):
#         return super().form_valid(form)
from .forms import Step2Forms

def step2A(request,pk):
    Book = Form.objects.get(id=pk)
    context = {'Book':Book} 
    if 'Book' not in request.POST:
        return render(request,'main/step2_Admin.html',context)
        # return render(request, "main/step2_Admin.html")
    else:
        booknumber = request.POST.get('Book',None)
        Book.booknumber = booknumber
        Book.save()
        return redirect('/main/Step2')
        # return render(request, "main:index")
    

def step2U(request):
    user = request.user.is_superuser
    if not user:
        form = Form.objects.get(user_id=request.user)
    else:
        form = Form.objects.all()
    context = {"form": form,}
    return render(request, "main/step2.html", context)

def step3 (request):
    files = Documentstep3.objects.all()
    if request.method == 'POST':
        form = Step3Forms(request.POST, request.FILES)
        filename = form['filename'].value()
        
        if form.is_valid():
            form.save()
			# eachsubject(request, form['subjectid'].value())
            return redirect('Step3')
        else:
            print(form.errors)
    else:
        form = Step3Forms()
        return render(request, 'main/step3.html', {
        'form': form,
        'files' : files
    })

    return render(request, "main/step3.html")

def step4(request):
    files = Documentstep4.objects.all()

intern/main/templates/main/base_01.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="with=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
    crossorigin="anonymous"></script>

  <meta charset="utf-8">

  <!-- <link rel="stylesheet" href="{%static 'css/main.css' %}">
  
  <link rel="stylesheet" href="{%static 'css/step2.css' %}"> -->
  
  <link rel="stylesheet" href="{%static 'css/step.css' %}">
  <link rel="stylesheet" href="{%static 'css/dashboard_style.css' %}">
  <link rel="stylesheet" href="{%static 'css/admin_style.css' %}">

  <!-- <title>{% block title %}Django Auth Tutorial{% endblock %}</title> -->
</head>
{% comment %}
{% endcomment %}
<section class="header">
  <nav>
    <a href="{% url 'main:index' %}">
      {% load static %}
      <!-- <img src="{% static 'css/images/old_tulogo2.svg' %}" class="logo"/></a> -->
      <img src="{% static 'css/images/new_TU_internship_logo.svg' %}" class="logo"/></a>

    <div class="nav-links" id="navLinks">
      <ul>

        <li><a href="{% url 'main:index' %}">Home</a></li>
        <li><a href="{% url 'main:news' %}">Internship</a></li>
        <!-- <li><a href="#">Menu</a>
          <div class="sub-about">
            <ul>
              <a href="#"><li>sub1</li></a>
              <a href="#"><li>sub2</li></a>
              <a href="#"><li>sub3</li></a>
        </li>
      </ul>
    </div>
    </li> -->
    <li><a href="#" class="About">About</a>
      <div class="sub-about">
        <ul>
          <!-- <a href="#"><li>Contact us</li></a> -->
          <a href="https://github.com/cn332proj/cn332proj"><li>GitHub</li></a>
          <a href="https://www.youtube.com/watch?v=O9XSYX4t2m8"><li>Youtube</li></a>
        </ul>
      </div>
    </li>
    <!-- <li ><a href="#">Log In</a></li> -->
    <li><a href="{% url 'user:logout' %}">Log out</a></li>
    </ul>
    </div>
  </nav>
</section>
<section class="body">
  {% block content %}

  {% endblock %}
</section>

<section class="footer">

</section>

intern/main/templates/main/companylist.html
{% extends "main/base_01.html" %}
{%block content%}
<div class="containertable">
    <h1>All Courses</h1>
    <div class="table">
        <table class="content-table">
            <thead>
                <tr>
                    <th>bookmark</th>
                    <th>Company</th>
                    <th>Description</th>
                    <th>Published</th>
                    <th>Close</th>
                    <th>Major</th>
                    <th>Link</th>
                </tr>
            </thead>
            <tbody>
                {% for company in company %}
                <tr>
                    <th><input type="checkbox"></th>
                    <td>{{ company.Company}}</td>
                    <td>{{ company.Description}}</td>
                    <td>{{ company.Published}}</td>
                    <td>{{ company.close}}</td>
                    <td>computer</td>
                    <td><a href="{{ company.link }} ">Click</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    {% endblock %}

intern/main/templates/main/form.html
{%block content%}
<META charset='utf-8'>
<title>
  แบบฟอร์มขอหนังสือ ขอความอนุเคราะห์ฝึกงานภาคฤดูร้อน/สหกิจศึกษา
</title>
<style>
  p {
    font-family: Prompt;
    font-size: 50px;
  }
</style>

<body>
  <p> {{ form }}</p>
</body>

{% endblock %}

intern/main/templates/main/index.html
{% extends "main/base_01.html" %}
{%block content%}
{% load static %}

<!-- <div class="text-box">
  <h1> Public Relations </h1>
  <p> Please select your ingredient and enjoy your recipe</p>

  {% for new in news %}
  <img src="{{new.img.url}}">
  <h3>{{ new.header }}</h3>
  <p>{{ new.context }}</p>
  <a href="{% url 'main:news_content' new.id %}" class="read-more">detail</a>
  {% endfor %}

  <a href="{% url 'main:Step1' %}" class="hero-btn">START STEP</a>
</div> -->

<div class="box"></div>

<h2>Thammasat Internship<br>System</h2>

<div class="menu_box">
  
  <div class="card-area">
    <a href="{% url 'main:news' %}" class="card">
      <img src="{% static 'css/images/finding_icon.svg' %}">
      บริษัทที่เปิดรับนักศึกษาฝึกงาน
    </a>
    <a href="{% url 'main:Step1' %}" class="card">
      <img src="{% static 'css/images/process_1.svg' %}">
      เริ่มขั้นตอนการฝึกงานภาคฤดูร้อน
    </a>

  </div>

  <i><img src="{% static 'css/images/paper_plane.svg' %}"></i>
</div>



<br><br>

{%endblock%}

intern/main/templates/main/index_bak.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
  <meta name="viewport" content="with=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <meta charset="utf-8">
  <link rel="stylesheet" href="{%static 'css/base_main.css' %}">
</head>
{% block content %}
<section class="header">
  <nav>
    <a href="#">
      <div class="nav-links" id="navLinks">
        <ul>

          <li><a href="#">Home</a></li>
          <li><a href="{% url 'main:news' %}">Internship</a></li>
          <li><a href="#">Menu</a>
            <div class="sub-about">
              <ul>
                <li><a href="#">sub1</a></li>
                <li><a href="#">sub2</a></li>
                <li><a href="#">sub3</a></li>
          </li>
        </ul>
      </div>
      </li>
      <li><a href="#" class="About">About</a>
        <div class="sub-about">
          <ul>
            <li><a href="#">Contact us</a></li>
            <li><a href="#">Git Hub</a></li>
            <li><a href="#">Youtube</a></li>
          </ul>
        </div>
      </li>
      <!-- <li ><a href="#">Log In</a></li> -->
      <li><a href="{% url 'user:logout' %}">Log out</a></li>
      </ul>
      </div>
  </nav>
  <div class="text-box">
    <h1> Public Relations </h1>
    <p> Please select your ingredient and enjoy your recipe</p>
    {% for new in news %}
    <img src="{{new.img.url}}">
    <h3>{{ new.header }}</h3>
    <p>{{ new.context }}</p>
    <a href="{% url 'main:news_content' new.id %}" class="read-more">detail</a>
    {% endfor %}
    <a href="{% url 'main:start' %}" class="hero-btn">START STEP</a>
  </div>
</section>

{% endblock %}

intern/main/templates/main/news.html
{% extends "main/base_01.html" %}
{% load static %}

{%block content%}

<!-- <div class="empty-box-news"></div>

{% for news in news %}
<title> {{news.header }}</title>
<a href="{% url 'main:news_content' news.id %}" class="read-more">{{ news.header }}</a>
{% endfor %} -->

<section class="content_step">
    <div class="step">
        <h4>บริษัทที่เปิดรับนักศึกษาฝึกงาน</h4>
        <div class="news-feed">
        <ul>
        {% for news in news %}
        
        <a href="{% url 'main:news_content' news.id %}" class="news-read-more"><li>{{ news.header }}</li></a>
        
        {% endfor %}
        </ul>
    </div>
    </div>
</section>

{% endblock %}

intern/main/templates/main/step2.html
{% extends "main/base_01.html" %}
{%block content%}
{% load static %}

<section class="content_step">
  <div class="step">
      <h4>Step 2 : เอกสารคำร้องขอฝึกงาน</h4>
      <div class="centerS2">
        {% if form.booknumber is none %}
        
          <p class="textCenter">
          นักศึกษาโปรดรอการดำเนินการสักครู่<br>กรุณากลับมาตรวจเช็คในอีก 1-3 วันทำการ
          </p>
        

        {% else %}

        <a href="{% url 'main:Step2toPDF'  %}" class="genPDFbtn">สร้างเอกสารคำร้อง</a>
        <p class="desc">ให้นักศึกษาดาวโหลดไฟล์แล้วนำส่งบริษัท</p>
        <a href="{% url 'main:Step3'  %}" class="Next-btn">Next Step ></a>
        {% endif %}
      </div>
  </div>
  <section class="step-wizard">
      <ul class="step-wizard-list">
        <li class="step-wizard-item">
          <span class="progress-count">1</span>
          <span class="progress-label">Step 1</span>
        </li>
        <li class="step-wizard-item current-item">
          <span class="progress-count">2</span>
          <span class="progress-label">Step 2</span>
        </li>
        <li class="step-wizard-item  ">
          <span class="progress-count">3</span>
          <span class="progress-label">Step 3</span>
        </li>
        <li class="step-wizard-item">
          <span class="progress-count">4</span>
          <span class="progress-label">Step 4</span>
        </li>
        <li class="step-wizard-item">
          <span class="progress-count">5</span>
          <span class="progress-label">Step 5</span>
        </li>
      </ul>
    </section>
</section>
{%endblock%}

intern/main/templates/main/step2_Admin.html
{% extends "admin_manage/base_01.html" %}

{% load static %}

{%block content%} 
<div class="box_add_student"></div>

<div class="content">
  <div class="add_student_card">
    <h4>หมายเลขหนังสือ</h4>
    <form method="post">
      {% csrf_token %}
      <input type="text" required name="Book" placeholder="Book" class="input_box">
      <input type="submit" class="btn">
    </form>

    <i><img src="{% static 'css/images/paper_plane.svg' %}"></i>
  </div>
</div>


{%endblock%}

intern/main/templates/main/success.html
<center><h2><br><br>success!</h2></center>
<meta http-equiv="refresh" content="1; url={%url 'main:start' %}" />