intern/intern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('main/', include('main.urls')),
    path('admin_manage/', include('admin_manage.urls')),
]

urlpatterns += staticfiles_urlpatterns()

intern/main/urls.py
from django.urls import path
from . import views
from .views import *
app_name="main"

urlpatterns = [
    path("", views.index, name="index"),


    #ข่าว
    path('news', views.news, name="news"),
    path('news/<int:number>', views.news_content, name="news_content"),

    
    path('CompanyList', views.company, name="company"),
    path('Step1', Step1Form.as_view(), name="Step1"),
    path('Step2Admin',Step2Form.as_view(), name="Step2Admin"),
    path('Step2', views.step2U , name="Step2"),
    path('Step2/<str:pk>', views.step2A , name="Step2A"),
    path('Step1toPDF', views.Step1toPDF, name="Step1toPDF"),
    path('Step2toPDF', views.Step2toPDF, name="Step2toPDF"),
    path('Step3', views.step3, name="Step3"),
    path('Step4', views.step4, name="Step4"),
    path('Step5', views.step5, name="Step5"),
]
   

intern/user/urls.py
from django.urls import path

from . import views

app_name="user"

urlpatterns = [
	path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

intern/user/models.py
from django.db import models


class Student(models.Model):
	Student_pk = models.BigAutoField(auto_created=True, primary_key=True)
	Student_id = models.CharField(max_length=20 ,null=True)
	Student_prefix = models.CharField(max_length=5 ,null=True)
	Student_name_th = models.CharField(max_length=200 ,null=True)
	Student_name_en = models.CharField(max_length=200 ,null=True)
	Student_email = models.CharField(max_length=200 ,null=True)
	Student_faculty = models.CharField(max_length=200 ,null=True)
	Student_department = models.CharField(max_length=200 ,null=True)
	Student_step = models.IntegerField(default = 0 ,null=True)
# Create your models here.

intern/user/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User
import requests
import pandas as pd
# Create your views here.

def index(request):
    return redirect("/login")


def login_view(request):
    if request.user.is_authenticated:
        return redirect(reverse("main:index"))
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None and user.is_superuser :
            login(request, user)
            return redirect(reverse("admin_manage:admin_dashboard"))
        else:
            login_status = login_api(username,password)
            if  login_status == 200:
                user = authenticate(request, username=username, password=username)
                if user is not None:
                    login(request, user)
                    return redirect(reverse("main:index"))

            else:
                messages.info(request, "invalid Student ID or password")
    return render(request, 'user/login.html')
    

def logout_view(request):
    logout(request)
    messages.success(request, "Logged out.")
    return render(request, "user/login.html", {
        "messages": messages.get_messages(request)
    })


### login with tu api
def login_api(username,password):
    header = {
        'Content-Type': 'application/json',
        'Application-Key': 'TUdad3354636aacf9e1e7f8954bef241f8dd654708036bf06bf8ae703785b21bc985327cf4b0059571504984688553db30'
    }

    body = {"UserName" : username,"PassWord" : password}

    res = requests.post("https://restapi.tu.ac.th/api/v1/auth/Ad/verify", headers= header, json= body)

    return res.status_code

intern/user/templates/user/index.html
<a href="{% url 'user:logout' %}">Log out</a>

intern/user/templates/user/login.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>login</title>
        <link rel="stylesheet" type="text/css" href="{% static '/css/login.css' %}">
    </head>
    {% block body %}
      <form method="post" action="{% url 'user:login' %}" id="login-form" class="login-form" autocomplete="off" role="main">
          {% csrf_token %}
          <h1 class="a11y-hidden">Login Form</h1>
            <div>
              <label class="label-email">
                <input type="text" name="username" placeholder="Username">
                <span class="required">Username</span>
              </label>
              <label class="label-password">
                <input type="password" name="password" placeholder="Password">
                <span class="required">Password</span>
              </label>
            </div>
            <input type="submit" value="Login" >
            <figure aria-hidden="true">
              <div class="person-body"></div>
              <div class="neck skin"></div>
              <div class="head skin">
              <div class="eyes"></div>
              <div class="mouth"></div>
              </div>
              <div class="hair"></div>
              <div class="ears"></div>
              <div class="shirt-1"></div>
              <div class="shirt-2"></div>
            </figure>
          {% if messages %}
          {% for message in messages %}
          <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
          {% endfor %}
    {% endif %}

      </form>

{% endblock %}