intern/admin_manage/urls.py
from django.urls import path


from . import views

app_name="admin_manage"

urlpatterns = [
    path("add_student", views.add_student, name="add_student"),
    path("add_student2", views.add_student2, name="add_student2"),
    path("admin_dashboard", views.admin_dashboard, name="admin_dashboard"),
    
    path('Step2', views.step2U , name="Step2"),
]
   

intern/intern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('main/', include('main.urls')),
    path('admin_manage/', include('admin_manage.urls')),
]

urlpatterns += staticfiles_urlpatterns()

intern/main/urls.py
from django.urls import path
from . import views
from .views import *
app_name="main"

urlpatterns = [
    path("", views.index, name="index"),


    #ข่าว
    path('news', views.news, name="news"),
    path('news/<int:number>', views.news_content, name="news_content"),

    
    path('CompanyList', views.company, name="company"),
    path('Step1', Step1Form.as_view(), name="Step1"),
    path('Step2Admin',Step2Form.as_view(), name="Step2Admin"),
    path('Step2', views.step2U , name="Step2"),
    path('Step2/<str:pk>', views.step2A , name="Step2A"),
    path('Step1toPDF', views.Step1toPDF, name="Step1toPDF"),
    path('Step2toPDF', views.Step2toPDF, name="Step2toPDF"),
    path('Step3', views.step3, name="Step3"),
    path('Step4', views.step4, name="Step4"),
    path('Step5', views.step5, name="Step5"),
]
   

intern/user/urls.py
from django.urls import path

from . import views

app_name="user"

urlpatterns = [
	path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
]

intern/admin_manage/models.py
from django.db import models

# Create your models here.

intern/admin_manage/views.py
from django.shortcuts import render
from django.shortcuts import render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.models import User,auth
import csv
from user.models import Student
import codecs
from main.forms import *
# Create your views here.


def add_student(request):
    return render(request, "admin_manage/add_student.html")

def add_student2(request):
	row_stid=int(request.POST.get('column', ''));
	if request.method == 'POST' and request.FILES['sheet']:
			mysheet = request.FILES['sheet']

	csvreader = csv.reader(codecs.iterdecode(mysheet,'utf-8'))
	record = []

	for row in csvreader:
		if row[row_stid-1].isdigit():
			add_user = User.objects.create_user(
	            username = row[row_stid-1],
	            password = row[row_stid-1],
	            email = 'email@mail.com',
	            first_name = "name",
	            last_name = "sur",            
	            )
			add_user.save()
	messages.info(request,'add new student success!')

	return redirect("/admin_manage/add_student")

	
def admin_dashboard(request):
    return render(request, "admin_manage/admin_dashboard.html")


def step2U(request):
    user = request.user.is_superuser
    if not user:
        form = Form.objects.get(user_id=request.user)
    else:
        form = Form.objects.all()
    context = {"form": form,}
    return render(request, "admin_manage/step2.html", context)

intern/admin_manage/templates/admin_manage/add_student.html
{% extends "admin_manage/base_01.html" %}
{% load static %}
{% block content %}

<div class="box_add_student"></div>

<div class="content">
<div class="add_student_card">
{% for i in messages%}
 <div class="alert alert-success" role="alert">   
  <br>
<center>{{i}}</center>  </div>
<meta http-equiv="refresh" content="4">
 {%endfor%} 


  <h4>ลงทะเบียนนักศึกษาใหม่</h4>
    <form action="{% url 'admin_manage:add_student2' %}"  method="post" enctype="multipart/form-data">
      {% csrf_token %}
  <br><br>

  <div class="content">
    <!-- <div class="set"> -->

      <div class="form-group">
        <label for="exampleInputEmail1">student id column : </label>
        <input type="text" class="form-control" name="column">
      </div>

      <div class="mb-3">
        <label for="formFile" class="form-label">sheet </label>
        <input class="form-control" type="file" name="sheet">
      </div>
      <br>
      <button type="submit" class="Add-btn">Add</button>           
        </form>

      <i><img src="{% static 'css/images/paper_plane.svg' %}"></i>
    </div>
</div>


{% endblock %}

intern/admin_manage/templates/admin_manage/admin_dashboard.html
{% extends "admin_manage/base_01.html" %}

{% block content %}
{% load static %}

{% for i in messages%}
 <div class="alert alert-success" role="alert">   
  <br>
<center>{{i}}</center>  </div>
<meta http-equiv="refresh" content="4">
 {%endfor%} 

<br><br>
<div class="box"></div>
<h2>Admin Dashboard</h2>
<!-- <br><br> -->

<div class="menu_box">
  
  <div class="card-area">
    <a href="{% url 'admin_manage:add_student' %}" class="card">
      <img src="{% static 'css/images/add_student_icon.svg' %}">
      ลงทะเบียนนักศึกษาใหม่
    </a>
    <a href="{% url 'admin_manage:Step2' %}" class="card">
      <img src="{% static 'css/images/docs_icon.svg' %}">
      ดูแบบฟอร์มขอความอนุเคราะห์
    </a>
  </div>

  <i><img src="{% static 'css/images/paper_plane.svg' %}"></i>
</div>



<br><br>
<!-- <h3> &nbsp;&nbsp;&nbsp; <a href="{% url 'user:logout' %}">logout</a> </h3><br> -->

{% endblock %}

intern/admin_manage/templates/admin_manage/base_01.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="with=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

  <meta charset="utf-8">

  <!-- <link rel="stylesheet" href="{%static 'css/main.css' %}">
  <link rel="stylesheet" href="{%static 'css/step.css' %}">
  <link rel="stylesheet" href="{%static 'css/admin_main.css' %}"> -->

<link rel="stylesheet" href="{%static 'css/admin_style.css' %}">
<link rel="stylesheet" href="{%static 'css/dashboard_style.css' %}">


  <!-- <title>{% block title %}Django Auth Tutorial{% endblock %}</title> -->
</head>




{% comment %} <!-- <h1>Public Relations</h1>
<h2><a href="{% url 'main:start' %}">START STEP</a></h2>
<a href="{% url 'user:logout' %}">Log out</a> --> {% endcomment %}

<section class="header">
    <nav>
      <a href="#">
        {% load static %}
        <img src="{% static 'css/images/new_TU_internship_logo.svg' %}" class="logo"/></a>
     
  <div class="nav-links" id="navLinks">
    <ul>
      
      <li><a href="{% url 'admin_manage:admin_dashboard' %}">Home</a></li>
      <!-- <li><a href="{% url 'main:news' %}">Internship</a></li>
      <li><a href="#">Menu</a>
        <div class="sub-about">
          <ul>
            <li><a href = "#" >sub1</a></li>
            <li><a href = "#" >sub2</a></li>
            <li><a href = "#" >sub3</a></li></li>
        </ul>
      </div>
      </li> -->
      <li><a href="#" class="About">About</a>
       <div class="sub-about">
            <ul>
              <a href="#"><li>Contact us</li></a>
              <a href="#"><li>Git Hub</li></a>
              <a href="#"><li>Youtube</li></a>
            </ul>
        </div>
      </li>
      <li ><a href="{% url 'user:logout' %}">Log out</a></li>
</ul></div>
</nav>
</section>


<section class="body">
{% block content %}
  
{% endblock %}
  </section>

<section class="footer">
  
</section>

intern/admin_manage/templates/admin_manage/step2.html
{% extends "admin_manage/base_01.html" %}

{% load static %}

{%block content%}  
<div class="box_add_student"></div>

<div class="content">
  <div class="add_student_card2">

<h1 class="heading">รายชื่อ<span>นักศึกษา</span></h1>
    {%if user.username == "admin" %}

      <h4 class="h4-admin">รายชื่อนักศึกษาที่รอหนังสือตอบกลับ</h4>
    <!-- <br> -->
    <div class="containertable">
      <div class="table">
          <table class="content-table">
              <thead>
                  <tr>
                      <th>ชื่อ-นามสกุล</th>
                  </tr>
              </thead>

              <tbody>
                  
                {% for student in form %}
                {%if student.booknumber is None %}
                  <tr>
                    <td><a href="{% url 'main:Step2A' student.id %}" class="name-l">{{student}}</a></td>
                  </tr>

                  
                  {% endif %}
                  {% endfor %}
              </tbody>
          </table>
      </div>
  </div>
   

    <h4 class="h4-admin">
    รายชื่อนักศึกษาที่ได้รับการตอบกลับแล้ว
    </h4>
    <!-- <br> -->

    <div class="containertable">
      <div class="table">
          <table class="content-table">
              <thead>
                  <tr>
                      <th>ชื่อ</th>
                      <th>นามสกุล</th>
                      <th>หมายเลขหนังสือ</th>
                  </tr>
              </thead>

              <tbody>
                  
                {% for list in form %}
                {%if list.booknumber is not None %}
                  <tr>
                      <td>{{list.name}}</td>
                      <td>{{list.sername}}</td>
                      <td>{{list.booknumber}}</td>
                  </tr>
                  {% endif %}
                  {% endfor %}
                  
              </tbody>
          </table>
      </div>
  </div>
  {% endif %}
</div>
</div>

{%endblock%}